### PR TITLE
[Bugfix] Revert upgrade presto-0.287

### PR DESCRIPTION
**Pull request by xiangyuf**
To close the issue: #36

### CODE REVIEW

**Comment by xiangyuf** [comment]
@JingsongLi @lanvendar pls review this when you have time.

**Comment by lanvendar** [comment]
pls compile without  test code,like this
mvn clean install -DskipTests -Dmaven.test.skip=true -am -pl paimon-presto-0.287 -Dpresto.version=0.287 -Dhadoop.apache2.version=2.7.4-12 -Dhive.apache.version=3.0.0-10
 

> @JingsongLi @lanvendar pls review this when you have time.

**Comment by xiangyuf** [comment]
> pls compile without test code,like this mvn clean install -DskipTests -am -pl paimon-presto-0.287 -Dpresto.version=0.287 -Dhadoop.apache2.version=2.7.4-12 -Dhive.apache.version=3.0.0-10
> 
> > @JingsongLi @lanvendar pls review this when you have time.

Still error.
image
 
 After revert 0.287,  the compilation could success.
image

**Comment by xiangyuf** [comment]
@JingsongLi @lanvendar Hi, in my humble opinion, we should revert the 0.287 upgrade first and introduce this later at least until it compiles.

**Comment by lanvendar** [comment]
> @JingsongLi @lanvendar Hi, in my humble opinion, we should revert the 0.287 upgrade first and introduce this later at least until it compiles.

The testing bug has been fixed. Please refer to my fork personal repository for details. I will apply for a merge later
image

**Comment by xiangyuf** [comment]
> > @JingsongLi @lanvendar   Hi, in my humble opinion, we should revert the 0.287 upgrade first and introduce this later at least until it compiles.
> 
> @xiangyuf The testing bug has been fixed. Please refer to my fork personal repository for details. I will apply for a merge later image

@lanvendar Looking forward for your MR.

**Review by JingsongLi — APPROVED** [review]
+1

**Pull request merged**
